{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "829416a0-85c4-481e-a582-0fbe334e65a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "from flask import Flask, render_template, request\n",
    "import random\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Predefined responses for a simple cancer chatbot\n",
    "responses = {\n",
    "    \"What is cancer?\": \"Cancer is a group of diseases involving abnormal cell growth with the potential to invade or spread to other parts of the body.\",\n",
    "    \"What are the symptoms of cancer?\": \"Symptoms can vary depending on the type of cancer but often include unusual lumps, unexplained weight loss, fatigue, skin changes, and persistent cough.\",\n",
    "    \"What are the causes of cancer?\": \"Cancer is caused by genetic mutations, which can result from factors such as smoking, radiation, viruses, cancer-causing chemicals, obesity, and lack of exercise.\",\n",
    "    \"How is cancer treated?\": \"Cancer treatment options include surgery, chemotherapy, radiation therapy, immunotherapy, and targeted therapy. The choice of treatment depends on the type and stage of cancer.\",\n",
    "    \"Can cancer be prevented?\": \"While not all cancers can be prevented, a healthy lifestyle can lower the risk. Avoiding tobacco, eating a balanced diet, maintaining a healthy weight, and regular screenings can help reduce the risk.\",\n",
    "    \"Tell me a fact about cancer.\": [\n",
    "        \"Over 9.6 million people die from cancer each year.\",\n",
    "        \"More than 70% of cancer deaths occur in low- and middle-income countries.\",\n",
    "        \"Lung, breast, and colorectal cancers are among the most common types of cancer.\"\n",
    "    ],\n",
    "    \"goodbye\": \"Thank you for chatting! Remember to consult a healthcare provider for any medical advice.\",\n",
    "    \"What is chemotherapy?\": \"Chemotherapy is a treatment that uses drugs to kill cancer cells or stop their growth.\",\n",
    "    \"What is immunotherapy?\": \"Immunotherapy is a treatment that uses the body's immune system to fight cancer by enhancing or stimulating the immune response.\",\n",
    "    \"What are the stages of cancer?\": \"Cancer stages describe the extent of cancer in the body. They are usually classified as Stage 0 (early) to Stage IV (advanced).\",\n",
    "    \"What is radiation therapy?\": \"Radiation therapy uses high-energy radiation to kill or damage cancer cells.\",\n",
    "    \"Can cancer be cured?\": \"Some types of cancer can be cured with early detection and treatment. However, other types may be managed as chronic conditions.\",\n",
    "    \"What is targeted therapy?\": \"Targeted therapy is a treatment that uses drugs to target specific genes or proteins that are involved in the growth and survival of cancer cells.\",\n",
    "    \"What is a biopsy?\": \"A biopsy is a procedure where a small sample of tissue is taken from the body to check for cancer cells.\",\n",
    "    \"Can genetics play a role in cancer?\": \"Yes, some cancers are hereditary, meaning they can run in families due to inherited gene mutations.\",\n",
    "    \"What is a tumor?\": \"A tumor is an abnormal mass of tissue that may or may not be cancerous. Benign tumors are non-cancerous, while malignant tumors are cancerous.\",\n",
    "    \"What is breast cancer?\": \"Breast cancer is a cancer that starts in the cells of the breast. It is one of the most common cancers in women.\",\n",
    "    \"What is lung cancer?\": \"Lung cancer is cancer that starts in the lungs, often due to smoking, although non-smokers can also develop lung cancer.\",\n",
    "    \"What is colon cancer?\": \"Colon cancer is cancer that starts in the colon (large intestine) or rectum, and is often associated with changes in bowel habits.\",\n",
    "    \"What is prostate cancer?\": \"Prostate cancer is cancer that starts in the prostate, a small gland that produces semen in men.\",\n",
    "    \"What is skin cancer?\": \"Skin cancer is cancer that begins in the skin cells, often caused by UV radiation exposure.\",\n",
    "    \"What are the risk factors for cancer?\": \"Risk factors include smoking, excessive alcohol consumption, obesity, family history, exposure to carcinogens, and lack of physical activity.\",\n",
    "    \"What are common cancer treatments?\": \"Common cancer treatments include surgery, chemotherapy, radiation therapy, immunotherapy, and targeted therapies.\",\n",
    "    \"What is cancer screening?\": \"Cancer screening involves tests and exams to detect cancer in people who do not yet have symptoms, with the aim of finding it early.\",\n",
    "    \"What is a cancer survivor?\": \"A cancer survivor is someone who has been diagnosed with cancer and is living with or after treatment.\",\n",
    "    \"What is a palliative care?\": \"Palliative care is specialized care aimed at relieving symptoms and improving quality of life for patients with serious illnesses like cancer.\",\n",
    "    \"How does smoking contribute to cancer?\": \"Smoking introduces carcinogens into the lungs and other parts of the body, significantly increasing the risk of lung and other cancers.\",\n",
    "    \"What foods should be avoided to prevent cancer?\": \"Processed foods, excessive red meat, and foods high in sugar or salt should be limited as they can increase cancer risk.\",\n",
    "    \"What foods are good for cancer prevention?\": \"A diet rich in fruits, vegetables, whole grains, and healthy fats is beneficial in reducing cancer risk.\",\n",
    "    \"Can exercise reduce cancer risk?\": \"Regular physical activity helps maintain a healthy weight and lowers the risk of various types of cancer, such as breast and colon cancer.\",\n",
    "    \"What is a clinical trial?\": \"A clinical trial is a research study to test new treatments or drugs for cancer.\",\n",
    "    \"What is a cancer vaccine?\": \"Cancer vaccines help the immune system recognize and destroy cancer cells. Examples include the HPV vaccine for cervical cancer.\",\n",
    "    \"How is cancer related to age?\": \"The risk of developing cancer increases with age, as the body accumulates mutations over time.\",\n",
    "    \"What is the survival rate for cancer?\": \"The survival rate depends on the type of cancer, its stage at diagnosis, and the treatment options available.\",\n",
    "    \"What is a cancer remission?\": \"Remission refers to the period when cancer signs and symptoms are reduced or disappear following treatment.\",\n",
    "    \"Can cancer spread to other parts of the body?\": \"Yes, cancer cells can spread from their original site to other parts of the body, a process known as metastasis.\",\n",
    "    \"What is an oncologist?\": \"An oncologist is a doctor who specializes in diagnosing and treating cancer.\",\n",
    "    \"What is a PET scan?\": \"A PET scan is a type of imaging test that can detect cancerous cells in the body.\",\n",
    "    \"What is a CT scan?\": \"A CT scan is a type of X-ray that provides detailed images of the body's organs and tissues and is often used to detect cancer.\",\n",
    "    \"What is a mammogram?\": \"A mammogram is an X-ray of the breast used to detect early signs of breast cancer.\",\n",
    "    \"What is HPV?\": \"Human papillomavirus (HPV) is a virus that can cause various cancers, including cervical cancer.\",\n",
    "    \"What is ovarian cancer?\": \"Ovarian cancer starts in the ovaries and is often diagnosed in later stages due to subtle symptoms.\",\n",
    "    \"What is liver cancer?\": \"Liver cancer starts in the liver, often due to chronic liver diseases like cirrhosis or hepatitis.\",\n",
    "    \"What is kidney cancer?\": \"Kidney cancer starts in the kidneys and may cause symptoms like blood in the urine or pain in the side.\",\n",
    "    \"What are the survival rates for breast cancer?\": \"Breast cancer survival rates vary depending on the stage, type, and treatment, with early detection improving outcomes.\",\n",
    "    \"Can cancer be treated with diet?\": \"While diet alone cannot cure cancer, a healthy diet can support overall health and may improve treatment outcomes.\",\n",
    "    \"What is a cancer recurrence?\": \"Cancer recurrence occurs when cancer comes back after treatment, either in the same location or elsewhere in the body.\",\n",
    "    \"What are the stages of breast cancer?\": \"Breast cancer stages range from Stage 0 (early) to Stage IV (advanced), depending on tumor size, lymph node involvement, and spread.\",\n",
    "    \"What is leukemia?\": \"Leukemia is a type of blood cancer that affects the bone marrow and blood cells.\",\n",
    "    \"What is the role of chemotherapy in cancer treatment?\": \"Chemotherapy kills cancer cells by interfering with their ability to divide and grow, but it can also affect healthy cells.\",\n",
    "    \"What is the importance of early detection in cancer?\": \"Early detection of cancer often leads to more effective treatments and higher survival rates.\",\n",
    "    \"What is the role of the immune system in fighting cancer?\": \"The immune system can recognize and attack cancer cells, and treatments like immunotherapy boost this natural defense.\",\n",
    "    \"How do environmental factors affect cancer risk?\": \"Exposure to environmental factors like air pollution, radiation, and chemicals can increase the risk of cancer.\"\n",
    "}\n",
    "\n",
    "def get_response(user_input):\n",
    "    # Check if input matches a key in the predefined responses\n",
    "    if user_input in responses:\n",
    "        response = responses.get[user_input]\n",
    "        # If the response is a list, choose a random fact\n",
    "        if isinstance(response, list):\n",
    "            return random.choice(response)\n",
    "        return response\n",
    "    else:\n",
    "        return \"I'm sorry, I don't have information on that. Please consult a medical professional for specific advice.\"\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return render_template(\"Chat.html\")\n",
    "\n",
    "@app.route(\"/get_response\", methods=[\"POST\"])\n",
    "def chat():\n",
    "    user_message = request.form[\"user_input\"]\n",
    "    bot_response = get_response(user_message)\n",
    "    return {\"response\": bot_response}\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "94d26c98-928d-48e3-9a27-5e55b238fb54",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "1e8138f3-392b-468c-ad97-983c4135e4d4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
